
script:
  - cd website
  - npm install
  - npm run publish-gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
